package alix.common.antibot.captcha;

import alix.common.utils.AlixCommonUtils;
import alix.common.utils.image.ImageGenerator;
import alix.fonts.AlixFontManager;

import java.awt.*;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.util.Random;

public final class CaptchaImageGenerator {

    private static final Font font = AlixFontManager.getPluginFont();
    private static final Random random = AlixCommonUtils.random;
    private static final X256Generator generatorX256 = new X256Generator();
    private static final DefaultGenerator generator = new DefaultGenerator();
    private static final ColorGenerator COLOR_GEN = ColorGenerator.IMPL;

/*    public static boolean filter(Color color) {//for map captcha
        int max = CaptchaImageGenerator.RBG_BOUND;
        int min = CaptchaImageGenerator.MIN_RGB;

        int red = color.getRed();
        int blue = color.getBlue();
        int green = color.getGreen();

        return red >= max || blue >= max || green >= max || red < min || blue < min || green < min;//the color was not generated by us
    }*/

    private CaptchaImageGenerator() {
    }

    public static BufferedImage resizeTo128(BufferedImage image) {
        BufferedImage resizedImage = new BufferedImage(128, 128, BufferedImage.TYPE_INT_ARGB);

        Graphics2D graphics = (Graphics2D) resizedImage.getGraphics();
        graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_OFF);

        Image scaledImage = image.getScaledInstance(128, 128, BufferedImage.TYPE_INT_ARGB);
        graphics.drawImage(scaledImage, 0, 0, 128, 128, null);

        return resizedImage;
    }

    public static BufferedImage generateCaptchaImageX256(String captcha, int maxRotation, boolean drawLines, boolean antialiasing) {
        return generatorX256.generate(captcha, maxRotation, drawLines, antialiasing);
    }

    public static BufferedImage generateCaptchaImage(String captcha, int maxRotation, boolean drawLines, boolean antialiasing) {
        return generator.generate(captcha, maxRotation, drawLines, antialiasing);
    }

    public static byte[] generateMapPixelsToDraw(String captcha, int maxRotation, boolean drawLines, boolean antialiasing) {
        return imageToBytes(generateCaptchaImage(captcha, maxRotation, drawLines, antialiasing));
    }

    private static int getRandomCoordinate() {
        return random.nextInt(128);
    }

    //private static boolean debugged = false;

    public static byte[] imageToBytes(BufferedImage image) {
        return ImageGenerator.imageToBytes(image);
    }

    private interface CaptchaImageGeneratorImpl {

        BufferedImage generate(String captcha, int maxRotation, boolean drawLines, boolean antialiasing);

    }

    private static final class X256Generator implements CaptchaImageGeneratorImpl {

        private X256Generator() {
        }

        @Override
        public BufferedImage generate(String captcha, int maxRotation, boolean drawLines, boolean antialiasing) {
            //image with alpha
            BufferedImage image = new BufferedImage(256, 256, BufferedImage.TYPE_INT_ARGB);//TYPE_INT_RGB - no alpha

            Canvas canvas = new Canvas();
            canvas.setSize(256, 256);

            Graphics2D graphics = (Graphics2D) image.getGraphics();
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, antialiasing ? RenderingHints.VALUE_ANTIALIAS_ON : RenderingHints.VALUE_ANTIALIAS_OFF);
            canvas.paint(graphics);

            graphics.setColor(Color.WHITE);
            graphics.fillRect(0, 0, 256, 256);

/*            try {
                File file = new File(plugin.getDataFolder(), "background.png");
                BufferedImage background = ImageIO.read(file);
                AffineTransform affineTransform = new AffineTransform();
                graphics.drawImage(background, affineTransform, null);
            } catch (Exception exception) {
                exception.printStackTrace();
            }*/

            int lines = drawLines ? random.nextInt(12) + 8 : 0;

            while (lines-- != 0) {
                graphics.setColor(COLOR_GEN.nextDifferentColor(null));
                graphics.drawLine(getRandomCoordinate(), getRandomCoordinate(), getRandomCoordinate(), getRandomCoordinate());
            }

            graphics.setFont(font);

            String[] chars = captcha.split("");

            Color lastColor = null;

            int sign = random.nextBoolean() ? 1 : -1;

            for (int i = 0; i != chars.length; i++) {
                AffineTransform original = graphics.getTransform();
                int rotation = random.nextInt((maxRotation << 1) + 1) - maxRotation;//generates a random number between -n & n

                int x = 70 + i * 25;
                int y = 130 + sign * 4;

                graphics.rotate(Math.toRadians(rotation), x, y);
                Color color = COLOR_GEN.nextDifferentColor(lastColor);
                lastColor = color;
                graphics.setColor(color);
                graphics.drawString(chars[i], x, y);
                sign *= -1;
                graphics.setTransform(original);
            }

            graphics.dispose();
            return image;
        }
    }

    //Source code: https://github.com/InstantlyMoist/Captcha/blob/master/src/main/java/me/kyllian/captcha/spigot/captchas/TextCaptcha.java

    private static final class DefaultGenerator implements CaptchaImageGeneratorImpl {

        private DefaultGenerator() {
        }

        @Override
        public BufferedImage generate(String captcha, int maxRotation, boolean drawLines, boolean antialiasing) {
            //image with alpha
            BufferedImage image = new BufferedImage(128, 128, BufferedImage.TYPE_INT_ARGB);//TYPE_INT_RGB - no alpha

            Canvas canvas = new Canvas();
            canvas.setSize(128, 128);

            Graphics2D graphics = (Graphics2D) image.getGraphics();
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, antialiasing ? RenderingHints.VALUE_ANTIALIAS_ON : RenderingHints.VALUE_ANTIALIAS_OFF);
            canvas.paint(graphics);

            graphics.setColor(Color.WHITE);
            graphics.fillRect(0, 0, 128, 128);

/*            try {
                File file = new File(plugin.getDataFolder(), "background.png");
                BufferedImage background = ImageIO.read(file);
                AffineTransform affineTransform = new AffineTransform();
                graphics.drawImage(background, affineTransform, null);
            } catch (Exception exception) {
                exception.printStackTrace();
            }*/

            int lines = drawLines ? random.nextInt(12) + 8 : 0;

            while (lines-- != 0) {
                graphics.setColor(COLOR_GEN.nextDifferentColor(null));
                graphics.drawLine(getRandomCoordinate(), getRandomCoordinate(), getRandomCoordinate(), getRandomCoordinate());
            }

            graphics.setFont(font);

            String[] chars = captcha.split("");

            Color lastColor = null;
            for (int i = 0; i != chars.length; i++) {
                AffineTransform original = graphics.getTransform();
                int rotation = random.nextInt((maxRotation << 1) + 1) - maxRotation;//generates a random number between -n & n
                graphics.rotate(Math.toRadians(rotation), 20 + i * 20, 64);
                Color color = COLOR_GEN.nextDifferentColor(lastColor);
                lastColor = color;
                graphics.setColor(color);
                graphics.drawString(chars[i], 20 + i * 20, 64);
                graphics.setTransform(original);
            }

            graphics.dispose();
            return image;
        }
    }



    //MapPalette end

    //Just some random stuff I found and skidded as well
/*    private static final class SomeGen implements ImageGenerator {

        private void drawCode(Graphics graphics, String code) {
            graphics.setColor(Color.WHITE);
            graphics.fillRect(0, 0, 128, 128);


            FontMetrics fontMetrics = graphics.getFontMetrics();
            int totalWidth = fontMetrics.stringWidth(code);
            int charGap = (128 - totalWidth) / (code.length() + 1);
            int x = charGap;
            int y = (128 - fontMetrics.getHeight()) / 2 + fontMetrics.getAscent();

            Random random = new Random();

            for (int i = 0; i < code.length(); i++) {
                graphics.setColor(getRandomColor());

                int charX = x + fontMetrics.charWidth(code.charAt(i)) / 2;
                int angle = random.nextInt(41) - 20;

                Graphics2D g2d = (Graphics2D) graphics;
                g2d.rotate(Math.toRadians(angle), charX, y);
                Font randomFont = font;
                graphics.setFont(randomFont);
                graphics.drawString(String.valueOf(code.charAt(i)), charX, y);
                g2d.rotate(-Math.toRadians(angle), charX, y);

                x += fontMetrics.charWidth(code.charAt(i)) + charGap;
            }
        }

        /*
        private void drawNoise(Graphics graphics) {
            Random random = new Random();
            for (int i = 0; i < 12; i++) {
                int x1 = random.nextInt(128);
                int y1 = random.nextInt(128);
                int x2 = x1 + random.nextInt(50) - 25;
                int y2 = y1 + random.nextInt(50) - 25;
                graphics.setColor(getRandomColor());
                graphics.drawLine(x1, y1, x2, y2);
            }
        }

        @Override
        public BufferedImage generate(String captcha, int maxRotation, boolean drawLines) {
            BufferedImage captchaImage = new BufferedImage(128, 128,
                    BufferedImage.TYPE_INT_RGB);
            Graphics2D graphics = captchaImage.createGraphics();

            drawCode(graphics, captcha);
            drawNoise(graphics);
            return captchaImage;
        }
    }*/


}